dist: trusty

sudo: false

language: php

matrix:
  include:
    - php: 5.6
      env: DB=PGSQL RECIPE_VERSION="^4.2" PHPUNIT_TEST=1
    - php: 7.1
      env: DB=PGSQL RECIPE_VERSION="^4.2" PHPUNIT_TEST=1
    - php: 7.2
      env: DB=MYSQL RECIPE_VERSION="^4.3" PHPUNIT_TEST=1
    - php: 7.3
      env: DB=MYSQL RECIPE_VERSION="^4.4" PHPUNIT_TEST=1 PHPCS_TEST=1
    - php: 7.3
      env: DB=MYSQL RECIPE_VERSION="^4" PHPUNIT_TEST=1

before_script:
  - phpenv rehash
  - phpenv config-rm xdebug.ini

  - composer validate
  - if [[ $DB == PGSQL ]]; then composer require --prefer-dist --no-update silverstripe/postgresql 2.1.x-dev; fi
  - composer require --no-update silverstripe/recipe-cms "$RECIPE_VERSION"
  - composer install --prefer-source --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

script:
  - if [[ $PHPUNIT_TEST ]]; then vendor/bin/phpunit; fi
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then phpdbg -qrr vendor/bin/phpunit --coverage-clover=coverage.xml; fi
  - if [[ $PHPCS_TEST ]]; then vendor/bin/phpcs src/ ; fi

after_success:
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then bash <(curl -s https://codecov.io/bash) -f coverage.xml; fi

